server:
  port: 8888

nginx:
  path:
    service: $CRUZ_ROOT/nginx/local/nginx/sbin/nginx
    conf: /home/cruzorcl/cruzlink/nginx/local/nginx/conf/nginx.conf
  cmd:
    status: curl localhost:8880/nginx_status
  log:
    path:
      status: /home/cruzorcl/cruzlink/nginx/nginx_api/logs/nginx_status.log
