server:
  port: 8888

nginx:
  path:
    service: $CRUZ_ROOT/nginx/local/nginx/sbin/nginx
    conf: $CRUZ_ROOT/nginx/local/nginx/conf/nginx.conf
  cmd:
    status: curl localhost:8880/nginx_status
  log:
    path:
      status: $CRUZ_ROOT/nginx/nginx_api/log/nginx_status.log
